packages:
  - .
  - docs/

allowBuilds:
  '@parcel/watcher': true
  '@prisma/engines': false
  core-js: false
  cpu-features: false
  esbuild: true
  prisma: false
  protobufjs: false
  sharp: true
  ssh2: false
  vue-demi: false

approveBuildsForPackages: '@parcel/watcher'

